version: '3.8'

services:
  # MQTT Broker (Mosquitto) for IoT Layer
  mqtt_broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./deployment/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # Backend API (FastAPI)
  microgrid_api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mqtt_broker

  # Frontend Dashboard (Streamlit)
  dashboard:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    command: streamlit run visualization_layer/dashboard.py
    ports:
      - "8501:8501"
    depends_on:
      - microgrid_api